#!/bin/bash

if [ -t 1 ] ; then
    export CSVN_WIDTH=$(tput cols)
    # Stdout is the terminal
    if [[ $# -gt 0 ]]; then
        case $1 in 
        diff)
            shift 1
            csvn diff "$@" | less
        ;;
        log)
            shift 1
            csvn log "$@" | less
        ;;
        logv)
            shift 1
            csvn log -v "$@" | less
        ;;
        *)
            # Used to allow interactive
            svn "$@"
        ;;
        esac
    else
        csvn
    fi
else
    svn "$@"
fi
